export const DEBATE_ABI = [
  // ── Read Functions ──
  {
    type: 'function',
    name: 'getInfo',
    inputs: [],
    outputs: [
      { name: 'creator', type: 'address', internalType: 'address' },
      { name: 'debateStatement', type: 'string', internalType: 'string' },
      { name: 'description', type: 'string', internalType: 'string' },
      { name: 'sideAName', type: 'string', internalType: 'string' },
      { name: 'sideBName', type: 'string', internalType: 'string' },
      { name: 'creationDate', type: 'uint256', internalType: 'uint256' },
      { name: 'endDate', type: 'uint256', internalType: 'uint256' },
      { name: 'isResolved', type: 'bool', internalType: 'bool' },
      { name: 'isSideAWinner', type: 'bool', internalType: 'bool' },
      { name: 'totalSideA', type: 'uint256', internalType: 'uint256' },
      { name: 'totalSideB', type: 'uint256', internalType: 'uint256' },
      { name: 'winnerReasoning', type: 'string', internalType: 'string' },
      { name: 'totalContentBytes', type: 'uint256', internalType: 'uint256' },
      { name: 'maxTotalContentBytes', type: 'uint256', internalType: 'uint256' },
      { name: 'totalBounty', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'status',
    inputs: [],
    outputs: [{ name: '', type: 'uint8', internalType: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getArgumentDataOnSideA',
    inputs: [],
    outputs: [
      { name: 'contents', type: 'string[]', internalType: 'string[]' },
      { name: 'amounts', type: 'uint256[]', internalType: 'uint256[]' },
      { name: 'authors', type: 'address[]', internalType: 'address[]' },
      { name: 'timestamps', type: 'uint256[]', internalType: 'uint256[]' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getArgumentDataOnSideB',
    inputs: [],
    outputs: [
      { name: 'contents', type: 'string[]', internalType: 'string[]' },
      { name: 'amounts', type: 'uint256[]', internalType: 'uint256[]' },
      { name: 'authors', type: 'address[]', internalType: 'address[]' },
      { name: 'timestamps', type: 'uint256[]', internalType: 'uint256[]' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getArgumentCountOnSideA',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getArgumentCountOnSideB',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getRemainingContentBytes',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getUserBets',
    inputs: [{ name: 'user', type: 'address', internalType: 'address' }],
    outputs: [
      { name: 'sideA', type: 'uint256', internalType: 'uint256' },
      { name: 'sideB', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'hasClaimed',
    inputs: [{ name: 'user', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalBounty',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'bountyContributions',
    inputs: [{ name: 'user', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'endDate',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  // ── Write Functions ──
  {
    type: 'function',
    name: 'claim',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'claimBountyRefund',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'cancelDebate',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
] as const;
